### PR TITLE
Added new Nigerian Phone Number Extensions and Validation Cretiria

### PR DESCRIPTION
**Pull request by Shamsuddeen**

### CODE REVIEW

**Comment by jeremyikwuje** [comment]
Hi @Shamsuddeen thanks for taking an interest.

But I think there's a problem with using the 4 prefixes. 

All those four prefixes you supplied have either of this ( 070, 080, 081, 090 ). Making it four will increase the check time and also require constant lookup for new prefixes.

Provide a valid benefit for increasing the prefixes.

**Comment by Shamsuddeen** [comment]
Adding four prefixes helps to decrease fake phone numbers, although the four prefixes will not stop it completely, but it will help much. Someone might type something like (0801) the first 3 prefixes will validate it as a valid phone number, while it is not (because of the fourth prefix), the Telcos have a unique identifier, which we usually determine the telco by the first four prefixes. We use the identifier to validate users phone number. Thanks

**Comment by jeremyikwuje** [comment]
I see, your point sounds reasonable. 

However, fourth prefixes are frequently added. 0801 is a possibility in the future.

How do we handle that?

**Comment by Shamsuddeen** [comment]
We then review the code and stay up-to-date.
There could also be another way to give it more standard

**Comment by Shamsuddeen** [comment]
Well understood. You have a great point

**Pull request closed without merging**
